## Numpy 
NumPy is a general-purpose array-processing packae. It provides a high performance multidimensonal array object, and tools for working with these arrays. It is the fundamental package for scientific computing with python.


## What is an array 
An array is a data structure that stores values of same data  type. In Python, this is the main difference between arrays and list. While python lists can contain values corresponding to different data types, arrays in  python can only contain values corresponding to same data type

In [11]:
import array as ar


In [12]:
import numpy as np

In [3]:
my_lst=[1,2,3,4,5,6]

In [4]:
arr=np.array(my_lst)

In [5]:
arr

array([1, 2, 3, 4, 5, 6])

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
arr.shape


(6,)

In [9]:
arr.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
print(arr)

[1 2 3 4 5 6]


In [11]:
print(arr.reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [13]:
l1=[1,2,3,4,5]
l2=[3,4,5,6,7]
l3=[4,5,6,7,8,]
arr=np.array([l1,l2,l3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [15]:
arr.shape

(3, 5)

In [16]:
arr[,2]

SyntaxError: invalid syntax (<ipython-input-16-3a55ece5be6b>, line 1)

In [17]:
arr[3]

IndexError: index 3 is out of bounds for axis 0 with size 3

In [18]:
arr[:]

array([[1, 2, 3, 4, 5],
       [3, 4, 5, 6, 7],
       [4, 5, 6, 7, 8]])

In [19]:
arr=np.array([1,2,3,45,6,7])

In [20]:
arr[4]

6

In [21]:
arr[0:2,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [22]:
arr[1:2,:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [23]:
arr[1:,3:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [24]:
arr[,3:]

SyntaxError: invalid syntax (<ipython-input-24-5a86bcbc6968>, line 1)

In [25]:
arr[0:,3:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [26]:
arr[1:,2:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [27]:
arr[1:,1:]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [29]:
arr=np.arange(0,10)

In [30]:
arr=np.arange(0,10,step=2)

In [31]:
arr

array([0, 2, 4, 6, 8])

In [32]:
np.lineshape(1,10,50)

AttributeError: module 'numpy' has no attribute 'lineshape'

In [33]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [34]:
# copy function
arr[3:]=100

In [35]:
ar

<module 'array' (built-in)>

In [36]:
arr

array([  0,   2,   4, 100, 100])

In [37]:
arr1=arr

In [38]:
arr1[3:]=500

In [39]:
arr

array([  0,   2,   4, 500, 500])

In [40]:
print(arr)
arr1[3:]=100
print(arr1)

[  0   2   4 500 500]
[  0   2   4 100 100]


In [44]:
val=2

In [45]:
arr>2

array([False, False,  True,  True,  True])

In [46]:
arr*2

array([  0,   4,   8, 200, 200])

In [47]:
arr[arr<2]

array([0])

In [48]:
arr[arr<300]

array([  0,   2,   4, 100, 100])

In [49]:
np.ones(4)

array([1., 1., 1., 1.])

In [50]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [52]:
np.ones((2,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [53]:
# Random distribution
np.random.rand(3,3)

array([[0.74385652, 0.10143612, 0.35356689],
       [0.86245412, 0.0056938 , 0.81675406],
       [0.16839846, 0.06390027, 0.27862467]])

In [57]:
arr2=np.random.randn(4,4)

In [58]:
arr2


array([[-1.24151492, -1.67306379, -0.03485851, -1.79005399],
       [-0.31976309, -0.76666288, -0.38304163, -0.33937132],
       [-2.04982777,  1.85608336,  1.39771089,  1.06507345],
       [-0.40734349, -0.51096916,  0.83517631, -0.24903216]])

In [59]:
import array as np

In [61]:
arr=np.array(1,2,6,7,7)

TypeError: array() takes at most 2 arguments (5 given)

In [41]:
# Some condition is very useful in Explanatory data Analysis
val=2
arr>2

array([False, False,  True,  True,  True])