In [1]:
import numpy as np

In [4]:
print(np.version)

<module 'numpy.version' from 'C:\\Users\\SAKIL MAHMUD\\anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [9]:
#  How to create a 1D array? printing array 
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
# How to create a boolean array?
np.full((3,3),True,dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [20]:
np.ones((3,3),dtype=bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [25]:
# Extract all odd numbers from  
arr=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[arr%2!=0]



array([1, 3, 5, 7, 9])

In [26]:
#How to replace items that satisfy a condition with another value in numpy array?
arr[arr%2==1]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [27]:
arr[arr%2!=0]=-1
arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [44]:
# How to replace items that satisfy a condition without affecting the original array?
arr=np.arange(10)
out=np.where(arr%2!=0,-1,arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [47]:
# How to reshape an array?
arr=np.arange(10)
arr.reshape(2,-1) # Setting to -1 automatically decides the number of cols

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [49]:
arr=np.arange(10)
arr.reshape(2,-1)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])